// DISPATCH API CALLS
export const GET_ALL_MISSIONS = 'GET_ALL_MISSIONS';
export const GET_ALL_LAUNCHES = 'GET_ALL_LAUNCHES';
export const GET_ALL_ROCKETS = 'GET_ALL_ROCKETS';

export const GET_ALL_ROCKETS_WITH_LAUNCHES = 'GET_ALL_ROCKETS_WITH_LAUNCHES';

// THREE
export const SET_RENDERER = 'SET_RENDERER';
export const SET_SCENE = 'SET_SCENE';
export const SET_CAMERA = 'SET_CAMERA';
export const SET_ROCKETS_SECTIONS = 'SET_ROCKETS_SECTIONS';
