export const GET_ALL_MISSIONS = 'GET_ALL_MISSIONS';
export const GET_ALL_LAUNCHES = 'GET_ALL_LAUNCHES';
export const GET_ALL_ROCKETS = 'GET_ALL_ROCKETS';
export const GET_ALL_ROCKETS_WITH_LAUNCHES = 'GET_ALL_ROCKETS_WITH_LAUNCHES';
